name: Open-source blog about Software Development and Architecture
description: Now you can make better existing posts about Development, Big Data, Architecture, R&D and Management or create your own.
meta_description: "Open-source notes and articles on High Load, Big Data, Java, Architecture and Management"

markdown: redcarpet
highlighter: pygments
logo: false
cover: true
paginate: 15
baseurl: /
disqus_shortname: rndblog-github
domain_name: 'http://rndblog.github.io'
google_analytics: 'UA-XXXXXXXX-X'

author:         'R&D Blog'
bio:		'Open-source notes and articles on High Load, Big Data, Java, Architecture and Management'

# Details for the RSS feed generator
url:            'http://rndblog.github.io'
