name: Software R&D blog
description: Now you can improve our posts
meta_description: "Open-source notes and articles on High Load, Big Data, Java, Architecture and Management"

markdown: kramdown
highlighter: pygments
logo: false
cover: true
paginate: 15
baseurl: /
disqus_shortname: rndblog-github
domain_name: 'http://rndblog.github.io'
google_analytics: 'UA-XXXXXXXX-X'

author:         'R&D Blog'
bio:		'Open-source notes and articles on High Load, Big Data, Java, Architecture and Management'

# Details for the RSS feed generator
url:            'http://rndblog.github.io'
license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Greative Commons License, BY-NC-SA</a>'
editable: true
