name: Open R&D blog
description: Now you can improve not only your posts. All about Software Development, Big Data, Architecture and Management
meta_description: "Open-source notes and articles on High Load, Big Data, Java, Architecture and Management"

markdown: redcarpet
highlighter: pygments
logo: false
cover: true
paginate: 15
baseurl: /
disqus_shortname: rndblog-github
domain_name: 'http://rndblog.github.io'
google_analytics: 'UA-XXXXXXXX-X'

author:         'R&D Blog'
bio:		'Open-source notes and articles on High Load, Big Data, Java, Architecture and Management'

# Details for the RSS feed generator
url:            'http://rndblog.github.io'
